[book]
authors = ["The Kevlar Authors"]
language = "en"
src = "."
title = "Kevlar Documentation"

[output.html]
git-repository-url = "https://github.com/levkropp/kevlar"
edit-url-template = "https://github.com/levkropp/kevlar/edit/main/Documentation/{path}"
