name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-release-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install apt packages
        run: sudo apt-get update && sudo apt-get install -y grub-pc xorriso mtools

      - name: Install cargo crates
        run: cargo install cargo-binutils rustfilt

      - name: Build an ISO image
        run: make RELEASE=1 iso

      - name: Generate changelog
        run: |
          cat > changelog.md << 'HEREDOC'
          Run the following command to try Kevlar on QEMU:
          ```
          qemu-system-x86_64 -m 512 -cpu Icelake-Server -serial mon:stdio \
              -device isa-debug-exit,iobase=0x501,iosize=2                \
              -netdev user,id=net0                                        \
              -device virtio-net,netdev=net0,disable-legacy=on            \
              -cdrom kevlar.iso
          ```
          HEREDOC
          echo >> changelog.md
          git shortlog $(git describe --tags --abbrev=0 @^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..@ >> changelog.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.md
          files: kevlar.iso
